[2025-03-24T08:41:46.419+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T08:41:46.441+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_eng_dag_etl.execute_snowflake_query manual__2025-03-24T08:41:43.196355+00:00 [queued]>
[2025-03-24T08:41:46.457+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_eng_dag_etl.execute_snowflake_query manual__2025-03-24T08:41:43.196355+00:00 [queued]>
[2025-03-24T08:41:46.457+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T08:41:46.480+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_snowflake_query> on 2025-03-24 08:41:43.196355+00:00
[2025-03-24T08:41:46.490+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T08:41:46.492+0000] {standard_task_runner.py:72} INFO - Started process 251 to run task
[2025-03-24T08:41:46.495+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_eng_dag_etl', 'execute_snowflake_query', 'manual__2025-03-24T08:41:43.196355+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/data-eng-dag-etl/dag.py', '--cfg-path', '/tmp/tmpxtdukgyf']
[2025-03-24T08:41:46.499+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask execute_snowflake_query
[2025-03-24T08:41:46.581+0000] {task_command.py:467} INFO - Running <TaskInstance: data_eng_dag_etl.execute_snowflake_query manual__2025-03-24T08:41:43.196355+00:00 [running]> on host cdc792c96e24
[2025-03-24T08:41:46.673+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_eng_dag_etl' AIRFLOW_CTX_TASK_ID='execute_snowflake_query' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T08:41:43.196355+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T08:41:43.196355+00:00'
[2025-03-24T08:41:46.674+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T08:41:46.708+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-03-24T08:41:46.709+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.36
[2025-03-24T08:41:46.713+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-24T08:41:46.713+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-24T08:41:58.726+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<snowflake.connector.vendored.urllib3.connection.HTTPSConnection object at 0x7618a87d8cb0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /session/v1/login-request?request_id=4ce41a3f-baa2-4ee8-85a0-9b958d2ef1eb&databaseName=RECRUITMENT_DB&schemaName=CANDIDATE_00184&warehouse=&roleName=&request_guid=189997d1-83f8-4204-90f6-8760428f2ce7
[2025-03-24T08:42:05.381+0000] {sql.py:511} INFO - Running statement: LIST @RECRUITMENT_DB.PUBLIC.S3_FOLDER, parameters: ;
[2025-03-24T08:42:05.382+0000] {connection.py:803} INFO - closed
[2025-03-24T08:42:05.629+0000] {connection.py:809} INFO - No async queries seem to be running, deleting session
[2025-03-24T08:42:05.917+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-eng-dag-etl/dag.py", line 27, in generate_ddl
    files = snowflake_connection('LIST @RECRUITMENT_DB.PUBLIC.S3_FOLDER')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-eng-dag-etl/dag.py", line 23, in snowflake_connection
    result = hook.get_first(command,";")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 336, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 465, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 964, in execute
    query = self._preprocess_pyformat_query(command, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 787, in _preprocess_pyformat_query
    query = command % processed_params
            ~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
[2025-03-24T08:42:05.931+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=data_eng_dag_etl, task_id=execute_snowflake_query, run_id=manual__2025-03-24T08:41:43.196355+00:00, execution_date=20250324T084143, start_date=20250324T084146, end_date=20250324T084205
[2025-03-24T08:42:05.967+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T08:42:05.968+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task execute_snowflake_query (not all arguments converted during string formatting; 251)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-eng-dag-etl/dag.py", line 27, in generate_ddl
    files = snowflake_connection('LIST @RECRUITMENT_DB.PUBLIC.S3_FOLDER')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-eng-dag-etl/dag.py", line 23, in snowflake_connection
    result = hook.get_first(command,";")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 336, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 465, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 964, in execute
    query = self._preprocess_pyformat_query(command, params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 787, in _preprocess_pyformat_query
    query = command % processed_params
            ~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: not all arguments converted during string formatting
[2025-03-24T08:42:06.020+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T08:42:06.049+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T08:42:06.055+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
